name: 'Organization Membership Check'
description: 'Checks if a user is a member of the dotCMS organization'

inputs:
  username:
    description: 'GitHub username to check'
    required: true

outputs:
  is_member:
    description: 'true if user is a member, false otherwise'
    value: ${{ steps.check-membership.outputs.is_member }}
  membership_status:
    description: 'Membership status (member, non-member, error)'
    value: ${{ steps.check-membership.outputs.membership_status }}

runs:
  using: 'composite'
  steps:
    - name: Check Organization Membership
      id: check-membership
      shell: bash
      run: |
        echo "Checking organization membership for user: ${{ inputs.username }} in dotCMS organization"

        # Use GitHub CLI to check organization membership
        # This uses the GITHUB_TOKEN which has read access to organization membership

        set +e  # Don't exit on error, we want to handle it gracefully

        # Check organization membership
        # The GitHub API returns different responses based on membership visibility:
        # - Public member: Returns user object with login field
        # - Private member: Returns empty response (200 OK but empty body)
        # - Non-member: Returns 404 error

        response=$(gh api orgs/dotCMS/members/${{ inputs.username }} 2>/dev/null)
        api_exit_code=$?

        if [ $api_exit_code -eq 0 ]; then
          # API call succeeded (either public or private member)
          if [ -n "$response" ]; then
            # Non-empty response means public membership
            echo "✅ User ${{ inputs.username }} is a member of dotCMS (public membership)"
          else
            # Empty response with 200 OK means private membership
            echo "✅ User ${{ inputs.username }} is a member of dotCMS (private membership)"
          fi
          echo "is_member=true" >> $GITHUB_OUTPUT
          echo "membership_status=member" >> $GITHUB_OUTPUT
        else
          # API call failed (404 = not a member, other errors = API issues)
          echo "❌ User ${{ inputs.username }} is not a member of dotCMS (API exit code: $api_exit_code)"
          echo "is_member=false" >> $GITHUB_OUTPUT
          echo "membership_status=non-member" >> $GITHUB_OUTPUT
        fi

        # Log the result for debugging (without leaking membership details)
        membership_result=$(if [ "$(cat $GITHUB_OUTPUT | grep 'is_member=true')" ]; then echo "AUTHORIZED"; else echo "UNAUTHORIZED"; fi)
        echo "::notice::Organization membership check result: $membership_result for ${{ inputs.username }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}