backend: &backend
  - '.github/workflows/maven-cicd-pipeline.yml'
  - 'bom/**'
  - 'build-parent/**'
  - 'core-web/pom.xml'
  - 'dotCMS/src/main/webapp/html/**/!(*.{css,js})'
  - 'dotcms-postman/**'
  - 'dotCMS/!(src/main/webapp/html/)**'
  - 'dotcms-integration/**'
  - 'independent-projects/**'
  - 'maven-plugins/**'
  - 'osgi-base/**'
  - 'parent/**'
  - 'plugins-core/**'
  - 'pom.xml'
  - 'reports/**'

frontend: &frontend
  - 'core-web/**'
  - 'dotCMS/src/main/webapp/html/**/*.{css,js}'

cli: &cli
  - 'tools/dotcms-cli/**'

sdkman: &sdkman
  -  '.sdkmanrc'

nvm: &nvm
  - '.nvmrc'

sdk:
  - 'core-web/libs/sdk/**'

jvm_unit_test:
  - *backend
  - *cli
  - *sdkman

build:
  - *backend
  - *cli
  - *frontend
  - *sdkman
  - *nvm
