name: 'Package CLI project'
description: 'Package the dotCMS CLI as an NPM project.'
inputs:
  branch:
    description: 'Branch to build from'
    required: false
    default: 'master'
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Download latest artifact
      id: download-cli-artifacts
      uses: dawidd6/action-download-artifact@v3.1.4
      with:
        github_token: ${{ inputs.github-token }}
        name: cli-artifacts-*
        name_is_regexp: true
        path: .
        if_no_artifact_found: warn        

    - name: 'List CLI Artifacts'
      if: ${{ steps.download-cli-artifacts.outputs.found_artifact == true }}
      run: |
        ls -R ${{ github.workspace }}
      shell: bash
