name: dotCLI Release trigger
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        
defaults:
  run:
    shell: bash

jobs:
  core-release:
    name: 'Pre-check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Log GitHub context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

