name: 'Setup GraalVM'
description: 'Setup GraalVM for Quarkus Native Images'
runs:
  using: 'composite'
  steps:
    # Sets up GRAALVM for native image compilation (Linux/macOS)
    # Downloads and installs GRAALVM
    # Configures environment variables
    - name: 'Set up GRAALVM for ${{ runner.os }}'
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: |
        CURRENT_JAVA_VERSION=$(java -version 2>&1 | awk -F[\"\"] '/version/ {print $2}' | awk -F[.] '{print $1}')
        
        echo "Using sdkman to install GraalVM"
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"

        current_version=$(sdk current java | sed 's/Using java version //' | tr -d '\n')

        if [ "$CURRENT_JAVA_VERSION" == "22" ]; then
          sdk install java 22.0.1-graalce
          GRAALVM_HOME=$(sdk home java 22.0.1-graalce)
        else
          sdk install java 21.0.2-graalce
          GRAALVM_HOME=$(sdk home java 21.0.2-graalce)
        fi

        echo "GRAALVM_HOME=$GRAALVM_HOME" >> "$GITHUB_ENV"
        gu install native-image
        sdk use java $current_version

    - name: 'Set up GRAALVM for (Windows)'
      if: ${{ inputs.buildNativeImage == true && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $CURRENT_JAVA_VERSION = (java -version 2>&1 | Select-String -Pattern 'version' | ForEach-Object { $_.Matches.Groups[1].Value } -split '\.' | Select-Object -First 1)
        $SDKMAN_DIR = "$env:USERPROFILE\.sdkman"
        if (-Not (Test-Path -Path $SDKMAN_DIR)) {
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.sdkman.io')
        }

        $env:SDKMAN_DIR = $SDKMAN_DIR
        . "$SDKMAN_DIR\bin\sdkman-init.sh"

        $current_version = & sdk current java | ForEach-Object { $_ -replace 'Using java version ', '' } | Out-String

        if ($CURRENT_JAVA_VERSION -eq "21") {
          sdk install java 21.0.2-graalce
          $GRAALVM_HOME = & sdk home java 21.0.2-graalce
        } elseif ($CURRENT_JAVA_VERSION -eq "22") {
          sdk install java 22.0.1-graalce
          $GRAALVM_HOME = & sdk home java 22.0.1-graalce
        }

        echo "GRAALVM_HOME=$GRAALVM_HOME" >> "$env:GITHUB_ENV"
        gu.cmd install native-image
        sdk use java $current_version