# action.yml
name: 'Prepare Runner'
description: 'Basic steps to prepare the runner'
inputs:
  cleanup-runner:
    description: 'The runner requires extra disk space'
    required: true
    default: 'false'
  no-java:
    description: 'Do not install Java'
    required: true
    default: 'false'
  graalvm:
    description: 'Install GraalVM'
    required: true
    default: 'false'
  require-master:
    description: 'require the master tag to run this action'
    required: true
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Setup master branch locally without switching current branch
      shell: bash
      if: (github.ref != 'refs/heads/master' && inputs.require-master == 'true')
      run: git fetch origin master:master
    - name: Cleanup Runner
      if: ${{ inputs.cleanup-runner == 'true' }}
      uses: ./.github/actions/cleanup-runner
    - name: Set GRAALVM_HOME from JAVA_HOME
      if: ${{ inputs.graalvm == 'true' }}
      shell: bash
      run: echo "GRAALVM_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - name: Setup Java (GraalVM)
      if: ${{ inputs.graalvm == 'true' }}
      id: sdkman-graalvm
      uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
      with:
        candidate: java
        version: 21.0.2-graalce
    - name: Setup Java # Uses .sdkmanrc file
      if: ${{ inputs.no-java == 'false' }}
      id: sdkman-java
      uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f