name: Merge Group Checks
on:
  merge_group:
    types: [checks_requested]
    branches: [master]
jobs:
  build-test:
    name: PR Build-Test
    uses: ./.github/workflows/reusable-ci-build-test.yml
    with:
      type: merge_group
      is-full: true
