name: Master Checks
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      reuse-previous-build:
        description: 'Indicates if the workflow should reuse the previous build'
        required: false
        type: boolean
        default: false
jobs:
  initialize:
    name: Initialize
    uses: ./.github/workflows/reusable-initialize.yml
    with:
      reuse-previous-build: ${{ inputs.reuse-previous-build || true }}
  build:
    name: PR Build
    needs: [ initialize ]
    if: needs.initialize.outputs.found_artifacts == 'false' && needs.initialize.outputs.build == 'true'
    uses: ./.github/workflows/reusable-ci-build.yml
    permissions:
      contents: read
      packages: write
  test:
    name: PR Test
    needs: [ initialize,build ]
    if: needs.*.success() || needs.build.skipped()
    uses: ./.github/workflows/reusable-ci-test.yml
    with:
      artifact-run-id: ${{ needs.initialize.outputs.artifact-run-id }}
      integration: ${{ needs.initialize.outputs.backend == 'true' }}
      postman: ${{ needs.initialize.outputs.backend == 'true' }}
      frontend: ${{ needs.initialize.outputs.frontend == 'true' }}
      cli: ${{ needs.initialize.outputs.cli == 'true' }}
      jvm_unit_test: ${{ needs.initialize.outputs.jvm_unit_test == 'true' }}
    secrets:
      DOTCMS_LICENSE: ${{ secrets.DOTCMS_LICENSE }}
  sonar:
    name: PR SonarQube
    needs: [ initialize,test ]
    uses: ./.github/workflows/reusable-sonarqube.yml
    with:
        run-id: ${{ needs.initialize.outputs.artifact-run-id }}
  finalize:
    name: Finalize
    needs: [ sonar ]
    uses: ./.github/workflows/reusable-finalize.yml
