name: Merge Group Checks - #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
on:
  merge_group:
    types: [checks_requested]
    branches: [master]
jobs:
  build-test:
    name: Build-Test # Must be the same for PR to use same required check names
    uses: ./.github/workflows/reusable-ci-build-test.yml
    with:
      type: merge_group
      build: all
      test: all
