name: Deploy SDKs

on:
  workflow_dispatch:      

jobs:
  deployment:
    runs-on: ubuntu-20.04
    # Use of Docker environments to enable per-deployment environment secrets
    # This allows for different secrets to be used based on the deployment environment
    environment: trunk
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Clean up the runner to ensure a fresh environment
      - uses: ./.github/actions/core-cicd/cleanup-runner

      - name: SDKs Publish
        id: sdks_publish
        uses: ./.github/actions/core-cicd/deployment/deploy-javascript-sdk
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TEST_TOKEN }}
      # Send Slack notification for SDK publication          
      - name: Slack Notification (SDK announcement)
        if: success() && steps.sdks_publish.outputs.published == 'true'
        uses: ./.github/actions/core-cicd/notification/notify-slack
        with:
          channel-id: "slack-notification-testing"
          payload: |
            > :large_orange_circle: *Attention dotters:* SDK libs (Angular, Client, Experiments and React) published!
            >
            > This automated script is happy to announce that a new *_SDK libs_* version *tagged as:* [ `${{ steps.sdks_publish.outputs.npm-package-version }}` ] is now available on the `NPM` registry :package:!
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}            
