name: dotCLI Release
on:
  release:
    types: [ created ]
    
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        default: '1.0.0-SNAPSHOT'
        required: false
        
  # workflow_run:
  #   workflows: ["dotCLI Release trigger"]
  #   types:
  #     - completed



concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  JAVA_VERSION: 11
  JAVA_DISTRO: temurin
  GRAALVM_VERSION: '22.1.0'
  MVN_PACKAGE_TYPE: 'uber-jar'
  NPM_PACKAGE_SCOPE: '@dotcms'
  NPM_PACKAGE_NAME: 'dotcli'
  MVN_PACKAGE_NAME: 'dotcms-cli'
  NODE_VERSION: 19

jobs:
  precheck:
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    name: 'Pre-check'
    runs-on: ubuntu-latest
    # outputs:
    #   RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
    #   HEAD: ${{ steps.version.outputs.HEAD }}
    #   AUXILIARY_BRANCH: ${{ steps.version.outputs.AUXILIARY_BRANCH }}
    #   DATE: ${{ steps.get-date.outputs.DATE }}    
    steps:
      - name: 'Log GitHub context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "::group::"
          echo "$GITHUB_CONTEXT"

          if [[ "$GITHUB_EVENT_NAME" == 'release' ]]; then
            TAG_NAME=${{ github.event.release.tag_name }}
            RELEASE_VERSION=${TAG_NAME:1}
          else
            RELEASE_VERSION=${{ inputs.version }}
          fi
          
          echo "::notice:: Event name: $GITHUB_EVENT_NAME"
          echo "::notice:: Release version: $RELEASE_VERSION"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "::endgroup::"

      - name: 'Checkout'
        uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.CI_MACHINE_TOKEN }}

      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      - uses: ./.github/actions/cleanup-runner
      - name: 'Get Date'
        id: get-date
        run: |
          echo "DATE=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT
        shell: bash

      - name: 'Restore Maven Repository'
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ steps.get-date.outputs.DATE }}-${{ github.run_id }}

      - name: 'Setup git config'
        run: |
          git config user.name dotCMS-Machine-Use
          git config user.email "dotCMS-Machine-User@dotcms.com"

      # Sets the release version and the next version
      # Creates an auxiliary branch for versioning updates
      - name: 'Set release version'
        id: version
        working-directory: ${{ github.workspace }}/tools/dotcms-cli
        run: |
          RELEASE_VERSION=$RELEASE_VERSION
          # RELEASE_VERSION=${{ github.event.inputs.version }}
          HEAD=${{ github.ref_name }}

          # Create a release branch for versioning updates
          AUXILIARY_BRANCH=version-update-${RELEASE_VERSION}-${{ github.run_id }}
          git checkout -b $AUXILIARY_BRANCH

          # Update version in pom.xml
          ./mvnw -B -ntp versions:set versions:commit -DnewVersion=$RELEASE_VERSION

          # Commit version changes
          git commit --allow-empty -a -m "Update dotCLI version to $RELEASE_VERSION"
          git push origin $AUXILIARY_BRANCH

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "HEAD=$HEAD" >> "$GITHUB_OUTPUT"
          echo "AUXILIARY_BRANCH=$AUXILIARY_BRANCH" >> "$GITHUB_OUTPUT"

  # Build native executable per runner
  build:
    needs: [ precheck ]
    name: 'Build native image on ${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-13-xlarge, macOS-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.precheck.outputs.AUXILIARY_BRANCH }}

      - name: 'Cleanup Runner'
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./.github/actions/cleanup-runner

      - name: 'Cleanup macOS Runner'
        if: ${{ contains(matrix.os, 'macos-') }}
        uses: ./.github/actions/cleanup-macos-runner

      # Sets up GraalVM for native image compilation (Linux/macOS)
      # Downloads and installs GraalVM
      # Configures environment variables
      - name: 'Set up GraalVM for (Linux/MacOS)'
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "GraalVM on Linux (AMD64)"

            ARCH=amd64
            PLATFORM=linux
            INSTALLATION_PATH=/usr/lib/jvm

          else
            if [ "${{ matrix.os }}" == "macos-13-xlarge" ]; then
              echo "GraalVM on Mac (AARCH64)"
              ARCH=aarch64
            else
              echo "GraalVM on Mac (AMD64)"
              ARCH=amd64
            fi

            PLATFORM=darwin
            INSTALLATION_PATH=/Library/Java/JavaVirtualMachines
          fi

          echo "PLATFORM=$PLATFORM"
          echo "ARCH=$ARCH"
          echo "INSTALLATION_PATH=$INSTALLATION_PATH"

          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.GRAALVM_VERSION }}/graalvm-ce-java11-${PLATFORM}-${ARCH}-${{ env.GRAALVM_VERSION }}.tar.gz
          sudo mkdir -p $INSTALLATION_PATH
          tar -xzf graalvm-ce-java11-${PLATFORM}-${ARCH}-${{ env.GRAALVM_VERSION }}.tar.gz
          sudo mv graalvm-ce-java11-${{ env.GRAALVM_VERSION }} $INSTALLATION_PATH

          if [ "${{ matrix.os }}" != "ubuntu-latest" ]; then
            sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/graalvm-ce-java11-${{ env.GRAALVM_VERSION }}/Contents/Home
            GRAALVM_HOME="${INSTALLATION_PATH}/graalvm-ce-java11-${{ env.GRAALVM_VERSION }}/Contents/Home"
          else
            GRAALVM_HOME="${INSTALLATION_PATH}/graalvm-ce-java11-${{ env.GRAALVM_VERSION }}"
          fi

          echo "GRAALVM_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
          echo "JAVA_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
          PATH="$GRAALVM_HOME/bin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
          gu install native-image

      - name: 'Set up GraalVM for (Windows)'
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          $ARCH="amd64"
          $DOWNLOAD_URL="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.GRAALVM_VERSION }}/graalvm-ce-java11-windows-${ARCH}-${{ env.GRAALVM_VERSION }}.zip"
          $OUTPUT_PATH="C:\graalvm-ce-java11-windows-${ARCH}-${{ env.GRAALVM_VERSION }}.zip"
          $GRAALVM_INSTALLATION_PATH="C:\Program Files (x86)\Java"

          Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile $OUTPUT_PATH

          if (Test-Path -Path $GRAALVM_INSTALLATION_PATH -PathType Container) {
            Write-Host "GRAALVM installation path exists."
          } else {
            Write-Host "Creating GRAALVM installation path."
            New-Item -ItemType Directory -Path $GRAALVM_INSTALLATION_PATH
          }

          Expand-Archive -Path $OUTPUT_PATH -DestinationPath $GRAALVM_INSTALLATION_PATH

          $env:JAVA_HOME="${GRAALVM_INSTALLATION_PATH}\graalvm-ce-java11-22.1.0"
          $env:Path="${env:Path};${env:JAVA_HOME}\bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64"

          echo "JAVA_HOME=${env:JAVA_HOME}" >> "$env:GITHUB_ENV"
          echo "Path=${env:Path}" >> "$env:GITHUB_ENV"

          gu.cmd install native-image

      - name: 'Cache Maven packages'
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ needs.precheck.outputs.DATE }}-${{ github.run_id }}

      - name: 'Prepare dotCMS license'
        env:
          DOTCMS_LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
        run: |
          DOTCMS_LICENSE_PATH=~/.dotcms/license
          mkdir -p ${DOTCMS_LICENSE_PATH}
          echo "${DOTCMS_LICENSE_KEY}" > ${DOTCMS_LICENSE_PATH}/license.dat
          echo "DOTCMS_LICENSE_FILE=${DOTCMS_LICENSE_PATH}/license.dat" >> "$GITHUB_ENV"

      - name: 'Compile source code'
        working-directory: ${{ github.workspace }}
        run: |
          ./mvnw clean install -Dtest.failure.ignore=true -DskipTests=true -am -pl :dotcms-cli

      - name: 'Build uber-jar'
        working-directory: ${{ github.workspace }}
        run: |
          ./mvnw package -Dquarkus.package.type=${{ env.MVN_PACKAGE_TYPE }} -DskipTests=true -pl :dotcms-cli

      # Builds a native image of the CLI using GraalVM (Linux/macOS)
      # Runs on a matrix for different operating systems
      - name: 'Build Native Image (Linux/MacOS)'
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: ${{ github.workspace }}
        run: |
          ./mvnw package -Pnative -DskipTests=true -pl :dotcms-cli

      # Builds a native image of the CLI using GraalVM on Windows
      # Uses PowerShell for setup and execution
      - name: 'Build Native Image (Windows)'
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          cmd /c 'call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && .\mvnw.cmd package -Dnative -DskipTests=true -pl :dotcms-cli'

      - name: 'Create distribution'
        working-directory: ${{ github.workspace }}
        run: |
          ./mvnw -B -ntp -Pdist package -DskipTests=true -pl :dotcms-cli

      - name: 'Distribution tree'
        working-directory: ${{ github.workspace }}/tools/dotcms-cli/
        run: |
          ls -ltr cli/target/distributions

      - name: 'Upload build artifact'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/tools/dotcms-cli/cli/target/*-runner.jar
            ${{ github.workspace }}/tools/dotcms-cli/cli/target/distributions/*.zip
            ${{ github.workspace }}/tools/dotcms-cli/cli/target/distributions/*.tar.gz
          
