name: 'CLI Build'
on:
  workflow_call:
    inputs:
      buildNativeImage:
        type: boolean
        required: true
      branch:
        type: string
        required: true
      artifact-run-id:
        default: ${{ github.run_id }}
        type: string
    outputs:
      artifact-id:
        description: 'The ID of the uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-id }}
      artifact-url:
        description: 'The URL of the uploaded artifact'
        value: ${{ jobs.build.outputs.artifact-url }}

env:
  JAVA_VERSION: 11
  JAVA_DISTRO: temurin
  GRAALVM_VERSION: '22.3.1'
  BRANCH: ${{ inputs.branch || github.ref_name }}
  SKIP_TESTS: true
  ARTIFACT_RUN_ID: ${{ inputs.artifact-run-id || github.run_id }}

defaults:
  run:
    shell: bash

jobs:
  os-runners:
    name: 'Get OS matrix'
    runs-on: ubuntu-latest
    outputs:
      runners: ${{ steps.set-os.outputs.runners }}
    steps:
      - name: 'Set OS'
        id: set-os
        run: |
          if [[ "${{ inputs.buildNativeImage }}" == "true" ]]; then
            RUNNERS='[{ "os": "ubuntu-latest", "label": "Linux" }, { "os": "macos-latest", "label": "macOS-Intel" }, { "os": "macos-13-xlarge", "label": "macOS-Silicon" }]'
          else
            RUNNERS='[{ "os": "ubuntu-latest", "label": "Linux" }]'
          fi
          echo "runners=$RUNNERS" >> $GITHUB_OUTPUT

  build:
    needs: os-runners
    name: 'Build native image on ${{ matrix.label }}'
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJSON( needs.os-runners.outputs.runners ) }}
    runs-on: ${{ matrix.os }}
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - uses: ./.github/actions/maven-job
        with:
          stage-name: "Build Native Image ${{ matrix.label }}"
          maven-args: "package -Pnative -DskipTests=$SKIP_TESTS -pl :dotcms-cli"
          native: true
          generates-test-results: true
          artifacts-from: ${{ env.ARTIFACT_RUN_ID }}


      - name: 'Upload built distribution'
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-artifacts-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/tools/dotcms-cli/cli/target/*.jar
            ${{ github.workspace }}/tools/dotcms-cli/cli/target/distributions/*.zip
            ${{ github.workspace }}/tools/dotcms-cli/api-data-model/target/*.jar
          retention-days: 2
          if-no-files-found: ignore