#  This job publish the dotCLI NPM package: @dotcms/dotcli@rc
#  every night. The package is built from the master branch.

name: dotCLI NPM build (nightly)
on:
  workflow_dispatch:

env:
  NPM_PACKAGE_NAME: 'dotcli'
  NPM_PACKAGE_SCOPE: '@dotcms'
  
jobs:
  build-package:
    name: Build NPM Package
    uses: ./.github/workflows/npm-packager.yml
    with:
      ref: master
      npm-package-name: $PACKAGE_NAME
      npm-package-scope: $NPM_PACKAGE_SCOPE
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write      

  publish-package:
    name: Publish NPM Package
    needs: [ build-package ]
    if: success()
    uses: ./.github/workflows/publish-npm-package.yml
    with:
      ref: master
      artifact-id: ${{ needs.create-package.outputs.artifact-id }}
      run-id: ${{ needs.create-package.outputs.run-id }}
      npm-package-version-tag: ${{ needs.create-package.outputs.npm-package-version-tag }}
    secrets:
        gh-pat: ${{ secrets.GITHUB_TOKEN }}
        npm-token: ${{ secrets.NPM_TOKEN }}
