#  This job publish the dotCLI NPM package: @dotcms/dotcms-cli@rc
#  every night. The package is built from the master branch.

name: Publish dotCLI NPM (nightly)
on:
  workflow_dispatch:

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - name: Create NPM Package
        uses: ./.github/actions/package-npm-cli
        with:
          branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}

