name: Prevent Upstream PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-target:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR targets upstream repository
        run: |
          # Check if this PR is targeting the upstream repository
          if [[ "${{ github.event.pull_request.base.repo.full_name }}" == "dotCMS/core" ]]; then
            echo "::error::❌ This PR is targeting the upstream repository (dotCMS/core)"
            echo "::error::This fork (core-workflow-test) is for testing workflow changes only."
            echo "::error::Please close this PR and create it in the correct repository."
            echo "::error::"
            echo "::error::If you meant to test workflows:"
            echo "::error::- Target 'main' branch in core-workflow-test repository"
            echo "::error::"
            echo "::error::If you meant to contribute to dotCMS/core:"
            echo "::error::- Create the PR directly in dotCMS/core repository"
            echo "::error::- Do not use this fork for actual contributions"
            exit 1
          else
            echo "✅ PR is correctly targeting the fork repository"
          fi

      - name: Add comment to upstream PR
        if: failure() && github.event.pull_request.base.repo.full_name == 'dotCMS/core'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ❌ Incorrect PR Target
            
            This PR is targeting the upstream repository (`dotCMS/core`), but it was created from the `core-workflow-test` fork.
            
            **This fork is for testing workflow changes only** - not for actual contributions to dotCMS/core.
            
            ### Please close this PR and:
            
            **If you're testing workflows:**
            - Target the `main` branch in the `core-workflow-test` repository
            - These PRs should stay within the fork for testing
            
            **If you're contributing to dotCMS/core:**
            - Create the PR directly in the `dotCMS/core` repository
            - Do not use this fork for actual contributions
            
            ### Why this restriction exists:
            - Prevents accidental PRs to the main repository during testing
            - Keeps workflow testing isolated in the fork
            - Maintains clear separation between testing and production contributions
            
            ---
            *This comment was automatically generated by the upstream PR prevention workflow*