name: 'Publish SDK libs'
on:
  push:
    branches: [ master ]

env:
  BRANCH: ${{ inputs.branch || github.ref_name }}
  NODE_VERSION: '19'
  
jobs:
  publish-sdk-on-npm:
    runs-on: ubuntu-20.04
    environment: trunk
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
          
      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: 'Checking affected files'
        id: checking-affected
        working-directory: ${{ github.workspace }}/core-web/
        run: |
          echo "::group::Checking affected files"
          pwd
          npm install
          AFFECTED=$(nx show projects --projects "sdk-*" --affected)

          if [[ -n "$AFFECTED" ]]; then
            PUBLISH='true'
          else
            PUBLISH='false'
          fi
          
          echo "publish=$PUBLISH" >> $GITHUB_OUTPUT
          echo "::endgroup::"
          
      - uses: ./.github/actions/publish-npm-sdks
        if: ${{ steps.checking-affected.outputs.publish == 'true' }}
        with:
          ref: ${{ env.BRANCH }}
          node-version: ${{ env.NODE_VERSION }}
          npm-token: ${{ secrets.NPM_ORG_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
