name: Reusable CI Build
on:
  workflow_call:
    inputs:
      core-build:
        type: boolean
        default: true

jobs:
  #
  # Initial JDK 11 Build
  # Basic build and install all with maven without running tests.
  # Provides local maven repo for subsequent steps
  #
  build-jdk11:
    name: "Initial Artifact Build"
    runs-on: ubuntu-20.04
    if: inputs.core-build == true
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/maven-job
        with:
          stage-name: "Initial Artifact Build"
          maven-args: "clean install -Pvalidate -DskipTests=true -Dgithub.event.name=${{ github.event_name }}"
          generate-artifacts: true
          require-master: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cleanup-runner: true
      - name: Check for changes to source during build
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo “Error: There are uncommitted changes in the working directory. These may have been modified by the build process.  Go back and run a full build before committing changes, or add these files to .gitignore if not required to be stored in the source to ensure the build is clean.”
            git status --porcelain
            exit 1
          else
            echo "No uncommitted changes found."
          fi