name: Tesing schedule
on:
  workflow_dispatch:
    inputs:
      publish-npm-package:
        type: boolean
        description: 'Publish NPM package?'
        default: true
  schedule:
    - cron: "18 3 * * *" # every night

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}      
        run: |
          echo "::group:: Github Context"
          echo "Event: $GITHUB_CONTEXT"
          echo "IS_WORKFLOW_DISPATCH: ${{ github.event.workflow_dispatch }}"
          echo "IS_SCHEDULE: ${{ github.event.schedule }}:
          echo "PUBLISH_NPM_PACKAGE: ${{ inputs.publish-npm-package }}"
          echo "::endgroup::"
