name: Tesing schedule
on:
  workflow_dispatch:
    inputs:
      publish-npm-package:
        type: boolean
        description: 'Publish NPM package?'
        default: false
        
  schedule:
    - cron: "3,6,9,12,15,18,21,24,27,30 * * * *"

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
          IS_WORKFLOW_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
          IS_SCHEDULE: ${{ github.event_name == 'schedule' }}
        run: |
          echo "::group:: Github Context"
          echo "Event: $GITHUB_CONTEXT"
          echo "IS_WORKFLOW_DISPATCH: $IS_WORKFLOW_DISPATCH"
          echo "IS_SCHEDULE: $IS_SCHEDULE"
          echo "PUBLISH_NPM_PACKAGE: ${{ inputs.publish-npm-package }}"
          echo "::endgroup::"

      - name: Checking status
        if: ${{ ( github.event_name == 'workflow_dispatch' && inputs.publish-npm-package == true ) || github.event_name == 'schedule' }}
        run: |
          echo "DATE: $(date +'%H:%M:%S')"
          echo "THIS STEP MUST BE RUN"
     
