name: Trunk Deployment
run-name: Trunk Deployment - ${{ github.event.workflow_run.name }}
concurrency: trunk-deployment  # move to deployment job if we need to queue up and not skip backlogged deployments
on:
  workflow_run:
    workflows: ['Maven CICD Pipeline']
    types: [completed]
permissions:
  contents: read
  actions: read # allow access to other job artifacts with GITHUB_TOKEN
jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest
    environment: trunk
    steps:
      # Should checkout from master referenced workflows need to be in master
      # for security reasons
      - name: Checkout core
        uses: actions/checkout@v4
      - name: Get the original commit SHA
        run:  |
          echo "The original commit SHA is ${{ github.event.workflow_run.head_sha }}"
          echo "The original run ID is ${{ github.event.workflow_run.id }}"
      - name: Build/Push Docker Image
        id: docker_build
        uses: ./.github/actions/deploy-artifact-docker
        with:
          docker_platforms: linux/amd64,linux/arm64
          build_run_id: ${{ github.event.workflow_run.id }}
          commit_id: ${{ github.event.workflow_run.head_sha }}"
          variant: master
          docker_tag: master_latest_SNAPSHOT
          do_deploy: false
          docker_io_username: ${{ secrets.DOCKER_USERNAME }}
          docker_io_token: ${{ secrets.DOCKER_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        if: github.repository == 'dotcms/core'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.DEVELOPERS_SLACK_WEBHOOK }}
          SLACK_USERNAME: dotBot
          SLACK_TITLE: "Attention dotters: Docker image built!"
          SLACK_MSG_AUTHOR: " "
          MSG_MINIMAL: true
          SLACK_FOOTER: ""
          SLACK_ICON: https://avatars.githubusercontent.com/u/1005263?s=200&v=4
          SLACK_MESSAGE: "This automated script is happy to announce that a new docker image has been built for *master* with tags: [${{ steps.docker_build.outputs.tags }}] :docker:"

