name: Trunk Deployment
run-name: Trunk Deployment - ${{ github.event.workflow_run.name }}
concurrency: trunk-deployment  # move to deployment job if we need to queue up and not skip backlogged deployments
on:
  workflow_run:
    workflows: ['Maven CICD Pipeline']
    types:
      - completed
    branches:
      - master
permissions:
  contents: read
  actions: read # allow access to other job artifacts with GITHUB_TOKEN
jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: trunk
    steps:
      # Should checkout from master referenced workflows need to be in master
      # for security reasons
      - name: Checkout core
        uses: actions/checkout@v4
      - name: Get the latest commit SHA from master
        id: latest_commit
        run: |
          echo "TRIGGER_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
          LATEST_SHA=$(git rev-parse origin/master)
          echo "LATEST_SHA=$LATEST_SHA" >> $GITHUB_ENV
          echo "The latest commit SHA is $LATEST_SHA"

      - name: Check if triggered by the latest commit
        if: env.TRIGGER_SHA != env.LATEST_SHA
        run: |
          echo "This workflow was triggered by an old commit. Latest commit SHA: $LATEST_SHA, Trigger commit SHA: $TRIGGER_SHA"
          exit 1  # This fails the step and cancels the deployment

      - name: Get the original commit SHA
        run:  |
          echo "The original commit SHA is ${{ github.event.workflow_run.head_sha }}"
          echo "The original run ID is ${{ github.event.workflow_run.id }}"
      - name: Build/Push Docker Image
        id: docker_build
        uses: ./.github/actions/deploy-artifact-docker
        with:
          docker_platforms: linux/amd64,linux/arm64
          build_run_id: ${{ github.event.workflow_run.id }}
          commit_id: ${{ github.event.workflow_run.head_sha }}"
          variant: master
          docker_tag: master_latest_SNAPSHOT
          do_deploy: false
          docker_io_username: ${{ secrets.DOCKER_USERNAME }}
          docker_io_token: ${{ secrets.DOCKER_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        if: github.repository == 'dotcms/core'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.DEVELOPERS_SLACK_WEBHOOK }}
          SLACK_USERNAME: dotBot
          SLACK_TITLE: "Attention dotters: Docker image built!"
          SLACK_MSG_AUTHOR: " "
          MSG_MINIMAL: true
          SLACK_FOOTER: ""
          SLACK_ICON: https://avatars.githubusercontent.com/u/1005263?s=200&v=4
          SLACK_MESSAGE: "This automated script is happy to announce that a new docker image has been built for *master* with tags: [${{ steps.docker_build.outputs.tags }}] :docker:"
